; ==============================================================================
; ContentCapture_Generated.ahk - Auto-Generated Hotstrings
; ==============================================================================
; This file is automatically generated by ContentCapture Pro.
; DO NOT EDIT MANUALLY - your changes will be overwritten!
;
; Hotstrings are generated from your captures.dat file each time
; the script loads or when you add/delete captures.
; ==============================================================================

; This file will be populated automatically when you start capturing content.
; Use Ctrl+Alt+P to capture your first webpage!

return
